# Configuration file with security issues

# VULNERABLE: Hardcoded credentials
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password123"
  name: "vulnerable_db"

# VULNERABLE: Weak JWT secret
jwt:
  secret: "secret"
  expiration: 8760h  # 1 year - too long

# VULNERABLE: Debug mode enabled
debug: true

# VULNERABLE: Insecure session settings
session:
  secret: "session-secret"
  secure: false
  httponly: false
  samesite: "none"

# VULNERABLE: No rate limiting
api:
  rate_limit: 0
  timeout: 300s

# VULNERABLE: Insecure logging
logging:
  level: "debug"
  log_passwords: true
  log_tokens: true

# VULNERABLE: CORS settings
cors:
  allowed_origins: ["*"]
  allowed_methods: ["*"]
  allowed_headers: ["*"]
  allow_credentials: true

# VULNERABLE: TLS settings
tls:
  enabled: false
  cert_file: ""
  key_file: ""
  min_version: "1.0"

# VULNERABLE: Admin credentials
admin:
  username: "admin"
  password: "admin123"
  api_key: "admin-secret-key"